### ISSUE TITLE
Add Cuda and CuDNN version

### ISSUE THREAD

**Issue by mratsim** [unicredit/nimcuda#1]
Hey Andrea,

Great work on the bindings, they work very well. Would it be possible to add the version of Cuda and CuDNN that you used in the readme. It seems to be Cuda 8 + CuDNN 5.1 currently.

Due to how Cuda/CuDNN depreciation works, deprecated or WIP procs temporarily get a version number like this one:
https://github.com/unicredit/nimcuda/blob/4bf458d13fe98380aa7241b891c1e850393ae57f/nimcuda/cudnn.nim#L275-L279

Those are then removed for ever (deprecated) or replace a "normal core" proc.

So between CuDNN v5.1 and CuDNN v7, some procs may have the same name but different arguments due to having been replaced, or others will have disappeared altogether.

**Comment by andreaferretti** [comment]
It is in fact CUDA 8 + CuDNN 5.1, I will add this
