### ISSUE TITLE
Windows dll names

### ISSUE THREAD

**Issue by WBosonic** [unicredit/nimcuda#3]
My CUDA installation (v8.0), uses this name convention:

*name*(64|32)_80.dll

while nimcuda expects *name*.dll.

I've worked around this by modifying the imported library names but I am wondering if there is something that I'm missing.

**Comment by WBosonic** [comment]
It looks like the correct way to use CUDA on windows is to use import libraries.

So statically link to `%CUDA_PATH%/lib/x64/name.lib` with the `passL` pragma instead of using the `dynlib` pragma, this will then point to the right dll to load.

I don't know if this is possible to generate with c2nim, c2nim seems to have some issues with macros if I try to generate the current code myself.

I don't even know if it is possible as it requires an optional `dynlib` based on os, the dynlibOverride flag can be used but then every windows users should need to set those flags.

**Comment by andreaferretti** [comment]
I am not familiar with Windows, and I have no way to test your changes. What do you suggest?

**Comment by WBosonic** [comment]
Something like this should do the trick:

```nim
when defined(windows):
  import os
  {.passL: "\"" & os.getEnv("CUDA_PATH") / "lib/x64" / "libname.lib" & "\"".}
  {.pragma: dyn.}
elif defined(macosx):
  const
    libName = "libname.dylib"
  {.pragma: dyn, dynlib: libName.}
else:
  const
    libName = "libname.so"
  {.pragma: dyn, dynlib: libName.}
```

Procs should then use `{.cdecl, dyn, importc: "someProcName".}` instead of the default ones c2nim gives them.

This requires rather much manual editing and unless you have a suggestion to automate this I'll do this when I have some time.

**Comment by andreaferretti** [comment]
Sorry, I don't know how to produce this using c2nim. When you find the time to do this and check that it works on windows, please update our PR. Thank you very much for our help!
