### ISSUE TITLE
tag new version with fixed docs

### ISSUE THREAD

**Issue by Vindaar** [unicredit/nimcuda#8]
Sorry, I forgot about this in my mini PR.

Could you tag a new version with the fixed docs?

The reason I made that PR was, because I'm trying to fix arraymancer's docs right now. If a new version is tagged, a freshly cloned arraymancer should get the new version and thus build the docs successfully.

**Comment by andreaferretti** [comment]
Done

**Comment by Vindaar** [comment]
Thanks a lot!
